"""Rename clubs.numero_usuario to numero_club

Revision ID: 192c6028dc0e
Revises: d3d48221825e
Create Date: 2025-04-09 12:16:37.701960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192c6028dc0e'
down_revision: Union[str, None] = 'd3d48221825e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('clubs',
                        'numero_usuario',                  # Nombre viejo en BD
                        new_column_name='numero_club',     # Nombre nuevo
                        existing_type=sa.VARCHAR(length=4), # Tipo existente en BD (era Varchar(4))
                        type_=sa.String(length=4),           # Tipo en el modelo (String(4))
                        nullable=False)
        # ### end Alembic commands ###

def downgrade() -> None:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('clubs',
                        'numero_club',                     # Nombre actual
                        new_column_name='numero_usuario',  # Nombre original
                        existing_type=sa.String(length=4),   # Tipo actual
                        type_=sa.VARCHAR(length=4),        # Tipo original
                        nullable=False)
        # ### end Alembic commands ###
