"""Cambiar FK de Campeonato a Club para usar codigo_club

Revision ID: da502fb91f42
Revises: f96920f1da5f
Create Date: 2025-04-15 09:31:46.335681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da502fb91f42'
down_revision: Union[str, None] = 'f96920f1da5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campeonatos', sa.Column('club_codigo', sa.String(length=6), nullable=False))
    op.create_index(op.f('ix_campeonatos_club_codigo'), 'campeonatos', ['club_codigo'], unique=False)
    op.drop_constraint('campeonatos_club_id_fkey', 'campeonatos', type_='foreignkey')
    op.create_foreign_key(None, 'campeonatos', 'clubs', ['club_codigo'], ['codigo_club'])
    op.drop_column('campeonatos', 'club_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campeonatos', sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campeonatos', type_='foreignkey')
    op.create_foreign_key('campeonatos_club_id_fkey', 'campeonatos', 'clubs', ['club_id'], ['id'])
    op.drop_index(op.f('ix_campeonatos_club_codigo'), table_name='campeonatos')
    op.drop_column('campeonatos', 'club_codigo')
    # ### end Alembic commands ###
