"""agregar_campos_contacto_club

Revision ID: e5f2185ed8a4
Revises: 
Create Date: 2025-03-17 15:45:52.135067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f2185ed8a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('persona_contacto', sa.String(length=200), nullable=True))
    op.add_column('clubs', sa.Column('telefono', sa.String(length=15), nullable=True))
    op.add_column('clubs', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('clubs', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('resultados', sa.Column('tipo_campeonato_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'resultados', 'tipos_campeonatos', ['tipo_campeonato_id'], ['id'])
    op.drop_column('resultados', 'tipo_campeonato')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados', sa.Column('tipo_campeonato', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resultados', type_='foreignkey')
    op.drop_column('resultados', 'tipo_campeonato_id')
    op.drop_column('clubs', 'email')
    op.drop_column('clubs', 'direccion')
    op.drop_column('clubs', 'telefono')
    op.drop_column('clubs', 'persona_contacto')
    # ### end Alembic commands ###
